apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-relationship-managment-root-application
  namespace: customer-relationship-managment-build
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rent-a-camel-idp/customer-relationship-managment-gitops.git
    path: components
    directory:
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: customer-relationship-managment-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=false      
    retry:
      limit: 0 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy