
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-app-03-build
  labels:
    app : test-app-03
    team: rms
    build-namespace: test-app-03-build
    size: small
    environment: build
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: test-app-03-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: test-app-03-dev
  labels:
    app : test-app-03
    team: rms
    build-namespace: test-app-03-build
    size: small
    environment: dev
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: test-app-03-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: test-app-03-qa
  labels:
    app : test-app-03
    team: rms
    build-namespace: test-app-03-build
    size: small
    environment: qa
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: test-app-03-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: test-app-03-prod
  labels:
    app : test-app-03
    team: rms
    build-namespace: test-app-03-build
    size: small
    environment: prod
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: test-app-03-build
