apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: rental-management
  description: manages camel rentals
  labels:
    size: small
    environments: build-dev-qa-prod
spec:
  owner: rms